In [1]:
import numpy as np

In [2]:
def backsub_one(lower,col,n):
  
    y[0] = col[0]/lower[0][0]
    for i in range(1,n):
        y[i] = col[i]
        for j in range(0,i):
            y[i] = y[i] - lower[i][j]*y[j]
        y[i]=y[i]/lower[i][i]
    return y

In [3]:
def backsub_two(upper,y,n):
   
   
    x[n-1] =y[n-1]/upper[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
    
        for j in range(i+1,n):
            x[i] = x[i] - upper[i][j]*x[j]
    
        x[i] = x[i]/upper[i][i]
    return x

In [4]:
n = int(input('Enter number of unknowns: '))

Enter number of unknowns: 3


In [5]:
mat = np.zeros((n,n))

In [6]:
upper=np.zeros((n,n))
lower=np.zeros((n,n))
y = np.zeros(n)
x = np.zeros(n)
#col = np.zeros(n)
ncol=np.zeros(n)
inv=np.zeros((n,n))


In [7]:
print('Enter Matrix Coefficients:')
for i in range(n):
    for j in range(n):
        mat[i][j] = float(input())#'mat['+str(i)+']['+ str(j)+']='))



Enter Matrix Coefficients:
15
8
25
45
65
47
27
10
7


In [8]:
#print('Enter the Coefficients of Column on RHS:')
#for i in range(n):
#    col[i]=float(input())

In [9]:
print(mat)

[[15.  8. 25.]
 [45. 65. 47.]
 [27. 10.  7.]]


In [10]:
for i in range(n): 
  
        # Upper Triangular 
        for k in range(i, n):  
  
            # Summation of L(i, j) * U(j, k) 
            sum = 0; 
            for j in range(i): 
                sum += (lower[i][j] * upper[j][k]); 
  
            # Evaluating U(i, k) 
            upper[i][k] = mat[i][k] - sum; 
        
        for k in range(i, n): 
            if (i == k): 
                lower[i][i] = 1; # Diagonal as 1 
            else: 
  
                # Summation of L(k, j) * U(j, i) 
                sum = 0; 
                for j in range(i): 
                    sum += (lower[k][j] * upper[j][i]); 
  
                # Evaluating L(k, i) 
                lower[k][i] = int((mat[k][i] - sum) /upper[i][i]);
   
  

In [11]:
print((lower))

[[1. 0. 0.]
 [3. 1. 0.]
 [1. 0. 1.]]


In [12]:
print((upper))

[[ 15.   8.  25.]
 [  0.  41. -28.]
 [  0.   0. -18.]]


In [13]:

for i in range(n):
    ncol[i]=1.0
    y1=backsub_one(lower,ncol,n)
    x1=backsub_two(upper,y1,n)
    for j in range(n):
        inv[j][i]=x1[j]
    ncol=np.zeros(n)

In [14]:
print (y1)

[0. 0. 1.]


In [15]:
print (x1)

[ 0.11282746 -0.03794038 -0.05555556]


In [16]:
print(inv)

[[-0.0071364  -0.01300813  0.11282746]
 [-0.03523035  0.02439024 -0.03794038]
 [ 0.05555556 -0.         -0.05555556]]
