###   Gaussian elimination


11* x- 8* y- 3* z = 15

8* x  - 23* y + 5 * z = 0

3* x + 5* y - 10 * z= 0

In [1]:
import numpy as np

In [2]:
n = int(input()) #input of no. of unknowns

3


In [3]:
a = np.zeros((n,n+1))

In [4]:
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
x = np.zeros(n)

In [6]:
print(x)

[0. 0. 0.]


In [7]:
#asking the user for input
print("Matrix Coeffecients")
for i in range(0,n):
    for j in range(0,n+1):
        a[i][j] = float(input())
        

Matrix Coeffecients
11
-8
-3
15
8
-23
5
0
3
5
-10
0


In [8]:
print(a)

[[ 11.  -8.  -3.  15.]
 [  8. -23.   5.   0.]
 [  3.   5. -10.   0.]]


In [9]:
# code for pivoting 
for i in range(0,n):
    flag = 1
    temp = i+1
    while(abs(a[i][i]) <= 0.001):
        if(temp==n):
            flag = 0
            print("Matrix unsolvable.")
            break;
        elif abs(a[temp][i]) > 0.001:
            for j in range(0,n+1):
                a[i][j], a[temp][j] =  a[temp][j], a[i][j]
        temp+=1
    if flag==1:
        for j in range(i+1,n):
            ratio = a[j][i]/a[i][i]
        
            for k in range(n+1):
                a[j][k] = a[j][k] - ratio * a[i][k]
    elif flag==0:
        break;

In [10]:
print(a)

[[ 11.          -8.          -3.          15.        ]
 [  0.         -17.18181818   7.18181818 -10.90909091]
 [  0.           0.          -6.17989418  -8.65079365]]


In [11]:
x[n-1] = a[n-1][n]/a[n-1][n-1]

In [12]:
for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    for j in range(i+1,n):
        x[i]= x[i] - a[i][j]*x[j]
    x[i] = x[i]/a[i][i]

In [13]:
print(x)

[2.63270548 1.22003425 1.39982877]
