In [1]:
import numpy as np

In [2]:
n = int(input('ENTER NUMBER OF UNKNOWNS:'))

ENTER NUMBER OF UNKNOWNS:3


In [3]:
def backsub_one(lower,col,n):
  
    y[0] = col[0]/lower[0][0]
    for i in range(1,n):
        y[i] = col[i]
        for j in range(0,i):
            y[i] = y[i] - lower[i][j]*y[j]
        y[i]=y[i]/lower[i][i]
    return y

In [4]:
def backsub_two(upper,y,n):
   
   
    x[n-1] =float(y[n-1]/upper[n-1][n-1])
    for i in range(n-2,-1,-1):
        x[i] = y[i]
    
        for j in range(i+1,n):
            x[i] = float(x[i] - upper[i][j]*x[j])
    
        x[i] = float(x[i]/upper[i][i])
    return x


In [5]:
matrix = np.zeros((n,n))

In [6]:
upper=np.zeros((n,n))
lower=np.zeros((n,n))
y = np.zeros(n)
x = np.zeros(n)
col = np.zeros(n)
inv=np.zeros((n,n))


In [7]:
print('ENTER AUGMENTED MATRIX COEFFICIENTS:')
for i in range (n):
    for j in range (n):
        matrix[i][j]= float(input())


ENTER AUGMENTED MATRIX COEFFICIENTS:
25
21
65
12
52
33
10
14
12


In [8]:
 print(matrix)

[[25. 21. 65.]
 [12. 52. 33.]
 [10. 14. 12.]]


In [9]:
for i in range(n):
    
    for k in range(i,n):
        sum = 0;
        for j in range(i):
            sum += (lower[i][j]*upper[j][k]);
            
        upper[i][k] = float(matrix[i][k]- sum);
    
    
    for k in range(i,n):
        if (i== k):
            lower[i][i] = 1;
        else:
            sum=0;
            for j in range(i):
                sum += (lower[k][j] * upper[j][i]);
                
            lower[k][i]= float((matrix[k][i] - sum)/ upper[i][i]);
            
        

In [10]:
print((upper))

[[ 25.          21.          65.        ]
 [  0.          41.92         1.8       ]
 [  0.           0.         -14.24045802]]


In [11]:
print((lower))

[[1.         0.         0.        ]
 [0.48       1.         0.        ]
 [0.4        0.13358779 1.        ]]


In [12]:
print('ENTER THE COEFFICIENTS OF COLUMN ON RHS:')
for i in range (n):
    col[i]= float(input())

ENTER THE COEFFICIENTS OF COLUMN ON RHS:
74
12
36


In [13]:
for i in range(n):
    
    y1=backsub_one(lower,col,n)
    x1=backsub_two(upper,y1,n)
    

In [15]:
print(x1)

[ 5.14928973 -0.53229697 -0.67006165]
