SOLVING NETWORK PROBLEM USING LU DECOMPOSITION

THE EQUATIONS ARE:
11*i1- 8*i2- 3*i3 = 15

8*i1 - 23*i2 + 5 *i3 = 0

3*i1 + 5*i2 - 10 *i3= 0

In [3]:
import math
import numpy as np
import matplotlib.pyplot as plt

In [4]:
n = int(input('ENTER NUMBER OF UNKNOWNS:'))

ENTER NUMBER OF UNKNOWNS:3


In [5]:
def bsub_one(lower,col,n):
  
    y[0] = col[0]/lower[0][0]
    for i in range(1,n):
        y[i] = col[i]
        for j in range(0,i):
            y[i] = y[i] - lower[i][j]*y[j]
        y[i]=y[i]/lower[i][i]
    return y

def bsub_two(upper,y,n):
   
   
    x[n-1] =float(y[n-1]/upper[n-1][n-1])
    for i in range(n-2,-1,-1):
        x[i] = y[i]
    
        for j in range(i+1,n):
            x[i] = float(x[i] - upper[i][j]*x[j])
    
        x[i] = float(x[i]/upper[i][i])
    return x

matrix = np.zeros((n,n))
upper=np.zeros((n,n))
lower=np.zeros((n,n))
y = np.zeros(n)
x = np.zeros(n)
col = np.zeros(n)
inv=np.zeros((n,n))
print('ENTER AUGMENTED MATRIX COEFFICIENTS:')
for i in range (n):
    for j in range (n):
        matrix[i][j]= float(input())


ENTER AUGMENTED MATRIX COEFFICIENTS:
11
-8
-3
8
-23
5
3
5
-10


In [6]:
 print(matrix)

[[ 11.  -8.  -3.]
 [  8. -23.   5.]
 [  3.   5. -10.]]


In [7]:
for i in range(n):
    
    for k in range(i,n):
        sum = 0;
        for j in range(i):
            sum += (lower[i][j]*upper[j][k]);
            
        upper[i][k] = float(matrix[i][k]- sum);
    
    
    for k in range(i,n):
        if (i== k):
            lower[i][i] = 1;
        else:
            sum=0;
            for j in range(i):
                sum += (lower[k][j] * upper[j][i]);
                
            lower[k][i]= float((matrix[k][i] - sum)/ upper[i][i]);
            

In [9]:
print((upper))

[[ 11.          -8.          -3.        ]
 [  0.         -17.18181818   7.18181818]
 [  0.           0.          -6.17989418]]


In [10]:
print((lower))

[[ 1.          0.          0.        ]
 [ 0.72727273  1.          0.        ]
 [ 0.27272727 -0.41798942  1.        ]]


In [11]:
print('ENTER THE COEFFICIENTS OF COLUMN ON RHS:')
for i in range (n):
    col[i]= float(input())

ENTER THE COEFFICIENTS OF COLUMN ON RHS:
15
0
0


In [12]:
for i in range(n):
    
    y1=bsub_one(lower,col,n)
    x1=bsub_two(upper,y1,n)

In [13]:
print(x1)

[2.63270548 1.22003425 1.39982877]
